version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: pii-next-app
    ports: 
      - '3000:3000'
    environment:
      - PORT=3000
    volumes:
      - .:/app
      - /app/node_modules
      - /app/.next