name: Backend CI

on:
  push:
    branches: [ "main" ]

defaults:
  run:
    working-directory: ./backend

jobs:

  build:
    runs-on: ubuntu-latest
    environment: backend-dev
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.21.6'

    - name: Create .env
      run: |
        echo "PORT=${{ secrets.PORT }}
        DATABASE_URL=${{ secrets.DATABASE_URL }}" > .env

    - name: Build
      run: |-
        go run github.com/steebchen/prisma-client-go generate \
        go build -v ./...
        